name: test
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  busted:
    name: tests
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup ‘lua’
      uses: leafo/gh-actions-lua@v9.1.0
      with:
        luaVersion: "5.1"

    - name: setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: setup dependencies
      run: |
        luarocks install busted
        luarocks install luacov-coveralls

    - name: run
      run: busted -c -v
      env:
        LUA_PATH: "/home/runner/work/tmux.nvim/tmux.nvim/?.lua;/home/runner/work/tmux.nvim/tmux.nvim/lua/?/init.lua;/home/runner/work/tmux.nvim/tmux.nvim/lua/?.lua;/home/runner/work/tmux.nvim/tmux.nvim/spec/?/init.lua;/home/runner/work/tmux.nvim/tmux.nvim/spec/?.lua;"

    - name: report
      if: success()
      continue-on-error: true
      run: luacov-coveralls -i tmux.nvim/lua -e .luarocks
      env:
        COVERALLS_REPO_TOKEN: ${{ github.token }}
        LUA_PATH: "/home/runner/work/tmux.nvim/tmux.nvim/?.lua;/home/runner/work/tmux.nvim/tmux.nvim/lua/?/init.lua;/home/runner/work/tmux.nvim/tmux.nvim/lua/?.lua;/home/runner/work/tmux.nvim/tmux.nvim/spec/?/init.lua;/home/runner/work/tmux.nvim/tmux.nvim/spec/?.lua;"
